### ISSUE TITLE
缺少 requirements

### ISSUE THREAD

**Issue by Initial-heart-1** [djkcyl/HeartBeatTracker#1]
如题，我想可能需要添加 requirements 文件。
对于 demo，测试通过的 requirements 如下：
```text
bleak==0.19.5
asyncio==3.4.3
fastapi==0.94.1
uvicorn==0.21.0
pathlib==1.0.1
loguru==0.6.0
websockets==10.4
```
另外 早就想研究研究心率广播怎么用了 这下可以直接抄了 60门🙏
Demo 在 HUAWEI Band HR-C22 上测试通过。其他设备可能需要改动 `need_name`。

**Comment by djkcyl** [comment]
正常的手环如果名字没被改过的话，不需要修改 need_name，华为手环的话都是带 Band 的，其他手环就不清楚了，也没有测试的环，已知小米手环是可以监听的，需要进入运动模式，但是延迟和广播间隔都很长，几乎不可用

**Comment by Initial-heart-1** [comment]
> 正常的手环如果名字没被改过的话，不需要修改 need_name，华为手环的话都是带 Band 的，其他手环就不清楚了，也没有测试的环，已知小米手环是可以监听的，需要进入运动模式，但是延迟和广播间隔都很长，几乎不可用

有没有这样一种可能，还有一种东西叫做手表（
